version: "3"

services:
  db:
    image: mysql:8.0.21
    container_name: banner_rotator_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: 'banner_rotator'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'