env: dev

http:
  host: app
  port: 8080

grpc:
  host: app
  port: 8081

logger:
  level: INFO
  file: logs/logger.json

database:
  host: mysql
  port: 3306
  user: user
  password: J1JyJovTelvERLF9
  name: banner_rotator

kafka:
  host: kafka
  port: 29092
  topic: banner_rotator_stat